version: '3.8'

services:
  backend:
    image: bimapangestu/volt-backend:v1.0.0
    environment:
      - MONGO_URI=mongodb://mongo:27017/volt
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
      - CORS_ORIGIN=https://volt.catalystlabs.id
      - WS_ORIGIN=wss://volt-api.catalystlabs.id
      - GIN_MODE=release
    networks:
      - volt-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    depends_on:
      - mongo
      - redis

  frontend:
    image: bimapangestu/volt-frontend:v1.0.0
    environment:
      - VITE_API_URL=https://volt-api.catalystlabs.id
      - VITE_WS_URL=wss://volt-api.catalystlabs.id
      - VITE_APP_NAME=Volt
      - VITE_BRAND_COLOR=#2563EB
    networks:
      - volt-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  mongo:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=volt
    volumes:
      - mongo_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - volt-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - volt-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Nginx reverse proxy (optional - if not using external load balancer)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - volt-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on:
      - backend
      - frontend

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  volt-network:
    driver: overlay
    attachable: true